# -*- coding: utf-8 -*-
"""Laboratório-Química.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhpS_r4pZMfZoHeVvOg7VND_Gcl3HXEA
"""

import random
import argparse
from collections import defaultdict
import statistics
from enum import Enum
import pandas as pd

INTERVALOS_POR_DIA = 10
DIAS = 5
TOTAL_INTERVALOS = INTERVALOS_POR_DIA * DIAS

class Equipamento:
    def __init__(self, nome, tempoMaximo, usosConsecutivos, limpeza):
        self.nome = nome
        self.tempoMaximo = tempoMaximo
        self.usosConsecutivos = usosConsecutivos
        self.limpeza = limpeza

    def __repr__(self):
        return f"{self.nome} (Tempo: {self.tempoMaximo}h, Usos máx: {self.usosConsecutivos})"


class Equipamentos(Enum):
    BALANCA_ANALITICA = Equipamento("Balança Analítica", 6, 3, False)
    AGITADOR_MAGNETICO = Equipamento("Agitador Magnético", 4, 4, False)
    CROMATOGRAFO_LIQUIDO = Equipamento("Cromatógrafo Líquido", 8, 4, False)
    CROMATOGRAFO_GASOSO = Equipamento("Cromatógrafo Gasoso", 6, 3, False)
    ESPECTROFOTOMETRO_UV_VIS = Equipamento("Espectrofotômetro UV-VIS", 4, 2, True)
    ESPECTROMETRO_INFRAVERMELHO = Equipamento("Espectrômetro Infravermelho", 6, 3, False)
    ESPECTROMETRO_DE_MASSA = Equipamento("Espectrômetro de Massa", 4, 2, True)
    MICROSCOPIO = Equipamento("Microscópio", 6, 4, False)
    CENTRIFUGA = Equipamento("Centrífuga", 6, 3, False)
    FORNO_DE_MUFLA = Equipamento("Forno de Mufla", 4, 2, True)


ANALISES = {
    1: [Equipamentos.ESPECTROFOTOMETRO_UV_VIS, Equipamentos.CROMATOGRAFO_GASOSO],
    2: [Equipamentos.CROMATOGRAFO_LIQUIDO, Equipamentos.ESPECTROMETRO_INFRAVERMELHO],
    3: [Equipamentos.MICROSCOPIO, Equipamentos.BALANCA_ANALITICA],
    4: [Equipamentos.ESPECTROMETRO_DE_MASSA],
    5: [Equipamentos.AGITADOR_MAGNETICO, Equipamentos.ESPECTROMETRO_INFRAVERMELHO],
    6: [Equipamentos.CROMATOGRAFO_LIQUIDO, Equipamentos.ESPECTROFOTOMETRO_UV_VIS],
    7: [Equipamentos.ESPECTROFOTOMETRO_UV_VIS, Equipamentos.MICROSCOPIO],
    8: [Equipamentos.CROMATOGRAFO_GASOSO],
    9: [Equipamentos.ESPECTROMETRO_INFRAVERMELHO, Equipamentos.BALANCA_ANALITICA],
    10: [Equipamentos.ESPECTROMETRO_DE_MASSA, Equipamentos.CROMATOGRAFO_GASOSO],
    11: [Equipamentos.CENTRIFUGA, Equipamentos.BALANCA_ANALITICA],
    12: [Equipamentos.AGITADOR_MAGNETICO, Equipamentos.CROMATOGRAFO_LIQUIDO],
    13: [Equipamentos.FORNO_DE_MUFLA, Equipamentos.ESPECTROMETRO_INFRAVERMELHO],
    14: [Equipamentos.ESPECTROFOTOMETRO_UV_VIS, Equipamentos.BALANCA_ANALITICA],
    15: [Equipamentos.CROMATOGRAFO_GASOSO, Equipamentos.ESPECTROMETRO_DE_MASSA],
    16: [Equipamentos.CENTRIFUGA, Equipamentos.CROMATOGRAFO_LIQUIDO],
    17: [Equipamentos.FORNO_DE_MUFLA, Equipamentos.MICROSCOPIO],
    18: [Equipamentos.BALANCA_ANALITICA, Equipamentos.AGITADOR_MAGNETICO, Equipamentos.ESPECTROFOTOMETRO_UV_VIS]
}

ANALISES_CRITICAS = [4, 10, 15]

def intervalo_para_dia(intervalo):
    return intervalo // INTERVALOS_POR_DIA

def individuo_aleatorio():
    individuo = []
    for a, seq_equipamentos in ANALISES.items():
        anterior = random.randint(0, TOTAL_INTERVALOS - 1)
        for i, membro_enum_equipamento in enumerate(seq_equipamentos):
            if i > 0:
                anterior += random.randint(2, 4)
            anterior = min(anterior, TOTAL_INTERVALOS - 1)
            individuo.append((a, i, anterior))
    return individuo

def aptidao(individuo):
    penalidade = 0
    uso_equipamento = defaultdict(list)
    uso_analise = defaultdict(list)

    for (a, i, intervalo) in individuo:
        membro_enum_equipamento = ANALISES[a][i]
        uso_equipamento[(membro_enum_equipamento, intervalo)].append(a)
        uso_analise[(a, intervalo)].append(i)

    for k, v in uso_equipamento.items():
        if len(v) > 1:
            penalidade += 100 * (len(v) - 1)

    for k, v in uso_analise.items():
        if len(v) > 1:
            penalidade += 100 * (len(v) - 1)

    por_analise = defaultdict(list)
    for (a, i, intervalo) in individuo:
        por_analise[a].append((i, intervalo))

    for a, etapas in por_analise.items():
        etapas.sort()
        for i in range(len(etapas) - 1):
            s1 = etapas[i][1]
            s2 = etapas[i+1][1]
            if s2 <= s1:
                penalidade += 80
            if s2 - s1 < 2:
                penalidade += 50

    uso_diario = defaultdict(int)
    for (a, i, intervalo) in individuo:
        membro_enum_equipamento = ANALISES[a][i]
        d = intervalo_para_dia(intervalo)
        uso_diario[(membro_enum_equipamento, d)] += 1

    for (membro_enum_equipamento, d), v in uso_diario.items():
        uso_maximo = membro_enum_equipamento.value.tempoMaximo
        if v > uso_maximo:
            penalidade += 120 * (v - uso_maximo)

    for (a, i, intervalo) in individuo:
        membro_enum_equipamento = ANALISES[a][i]
        if a in ANALISES_CRITICAS and membro_enum_equipamento.value.nome == "Espectrômetro de Massa":
            if intervalo >= 30:
                penalidade += 200

    PENALIDADE_R8 = 70

    linha_do_tempo_equipamento = defaultdict(lambda: [None] * TOTAL_INTERVALOS)
    for (a, i, intervalo) in individuo:
        membro_enum_equipamento = ANALISES[a][i]
        linha_do_tempo_equipamento[membro_enum_equipamento][intervalo] = a

    for membro_enum_equipamento in Equipamentos:
        if membro_enum_equipamento.value.limpeza:
            usos_consecutivos = 0
            for intervalo in range(TOTAL_INTERVALOS):
                if linha_do_tempo_equipamento[membro_enum_equipamento][intervalo] is not None:
                    usos_consecutivos += 1
                    if usos_consecutivos > membro_enum_equipamento.value.usosConsecutivos:
                        penalidade += PENALIDADE_R8
                else:
                    usos_consecutivos = 0

    makespan = max(intervalo for (_, _, intervalo) in individuo)

    return 10000 - penalidade - makespan * 5

def torneio(populacao, k=3):
    return max(random.sample(populacao, k), key=lambda x: x[1])[0]

def cruzamento(p1, p2):
    corte = random.randint(0, len(p1)-1)
    return p1[:corte] + p2[corte:]

def mutacao(individuo, taxa):
    novo_individuo = []
    for (a, i, intervalo) in individuo:
        if random.random() < taxa:
            intervalo = random.randint(0, TOTAL_INTERVALOS-1)
        novo_individuo.append((a, i, intervalo))
    return novo_individuo

def executar_ag(tamanho_populacao, geracoes, taxa_mutacao, taxa_cruzamento):
    populacao = [individuo_aleatorio() for _ in range(tamanho_populacao)]

    melhor_solucao_geral = None
    melhor_aptidao_geral = -float('inf')
    geracao_melhor_solucao = -1

    for geracao in range(geracoes):
        pontuados = [(ind, aptidao(ind)) for ind in populacao]
        pontuados.sort(key=lambda x: x[1], reverse=True)

        melhor_aptidao_atual = pontuados[0][1]
        media_aptidao = statistics.mean(x[1] for x in pontuados)
        pior_aptidao = pontuados[-1][1]

        if melhor_aptidao_atual > melhor_aptidao_geral:
            melhor_aptidao_geral = melhor_aptidao_atual
            melhor_solucao_geral = pontuados[0][0]
            geracao_melhor_solucao = geracao

        nova_populacao = [pontuados[0][0]]

        while len(nova_populacao) < tamanho_populacao:
            p1 = torneio(pontuados)
            p2 = torneio(pontuados)

            if random.random() < taxa_cruzamento:
                filho = cruzamento(p1, p2)
            else:
                filho = p1

            filho = mutacao(filho, taxa_mutacao)
            nova_populacao.append(filho)

        populacao = nova_populacao

    return melhor_solucao_geral, melhor_aptidao_geral, geracao_melhor_solucao

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--pop", type=int, default=50)
    parser.add_argument("--gen", type=int, default=100)
    parser.add_argument("--mut", type=float, default=0.1)
    parser.add_argument("--cross", type=float, default=0.8)

    argumentos = parser.parse_args([])

    melhor_solucao, melhor_aptidao_final, geracao_melhor_solucao = executar_ag(argumentos.pop, argumentos.gen, argumentos.mut, argumentos.cross)

    def formatar_intervalo_para_hora(numero_intervalo):
        hora_inicio_dia = 8
        hora = hora_inicio_dia + (numero_intervalo % INTERVALOS_POR_DIA)
        return f"{hora:02d}h-{hora+1:02d}h"

    nomes_dias = {0: "Segunda", 1: "Terça", 2: "Quarta", 3: "Quinta", 4: "Sexta"}

    dados_cronograma_analise = defaultdict(list)
    dados_cronograma_equipamento_brutos = defaultdict(list)

    for a, i, intervalo in melhor_solucao:
        membro_enum_equipamento = ANALISES[a][i]
        nome_equipamento = membro_enum_equipamento.value.nome
        indice_dia = intervalo_para_dia(intervalo)
        nome_dia = nomes_dias.get(indice_dia, f"Dia {indice_dia + 1}")
        intervalo_horas = formatar_intervalo_para_hora(intervalo)

        dados_cronograma_analise[a].append({
            "indice_etapa": i,
            "nome_equipamento": nome_equipamento,
            "intervalo": intervalo,
            "nome_dia": nome_dia,
            "indice_dia": indice_dia,
            "intervalo_horas": intervalo_horas
        })

        dados_cronograma_equipamento_brutos[membro_enum_equipamento].append({
            "id_analise": a,
            "nome_dia": nome_dia,
            "intervalo_horas": intervalo_horas,
            "intervalo": intervalo,
            "tipo": "analise",
            "indice_dia": indice_dia
        })

    linha_do_tempo_equipamento_para_exibir = defaultdict(lambda: [None] * TOTAL_INTERVALOS)
    for (a, i, intervalo) in melhor_solucao:
        membro_enum_equipamento = ANALISES[a][i]
        linha_do_tempo_equipamento_para_exibir[membro_enum_equipamento][intervalo] = (a, i)

    for membro_enum_equipamento in Equipamentos:
        if membro_enum_equipamento.value.limpeza:
            usos_consecutivos = 0
            for indice_intervalo in range(TOTAL_INTERVALOS):
                if linha_do_tempo_equipamento_para_exibir[membro_enum_equipamento][indice_intervalo] is not None:
                    usos_consecutivos += 1
                    if usos_consecutivos > membro_enum_equipamento.value.usosConsecutivos:
                        intervalo_limpeza = indice_intervalo + 1
                        if intervalo_limpeza < TOTAL_INTERVALOS:
                            indice_dia_limpeza = intervalo_para_dia(intervalo_limpeza)
                            nome_dia_limpeza = nomes_dias.get(indice_dia_limpeza, f"Dia {indice_dia_limpeza + 1}")
                            intervalo_horas_limpeza = formatar_intervalo_para_hora(intervalo_limpeza)
                            dados_cronograma_equipamento_brutos[membro_enum_equipamento].append({
                                "id_analise": "[bloqueado para limpeza]",
                                "nome_dia": nome_dia_limpeza,
                                "intervalo_horas": intervalo_horas_limpeza,
                                "intervalo": intervalo_limpeza,
                                "tipo": "limpeza",
                                "indice_dia": indice_dia_limpeza
                            })
                else:
                    usos_consecutivos = 0

    eventos_equipamento_agrupados_diariamente = defaultdict(lambda: defaultdict(list))

    for membro_enum_equipamento, eventos in dados_cronograma_equipamento_brutos.items():
        for evento in eventos:
            eventos_equipamento_agrupados_diariamente[evento['indice_dia']][membro_enum_equipamento].append(evento)

    lista_analise = []
    for id_analise, etapas in sorted(dados_cronograma_analise.items()):
        etapas.sort(key=lambda x: x['intervalo'])

        ultimo_intervalo = etapas[-1]['intervalo'] if etapas else None
        indice_dia_conclusao = intervalo_para_dia(ultimo_intervalo) if ultimo_intervalo is not None else None
        nome_dia_conclusao = nomes_dias.get(indice_dia_conclusao, f"Dia {indice_dia_conclusao + 1}") if indice_dia_conclusao is not None else "N/A"
        hora_conclusao = 8 + (ultimo_intervalo % INTERVALOS_POR_DIA) + 1 if ultimo_intervalo is not None else "N/A"

        for i, etapa in enumerate(etapas):
            lista_analise.append({
                "Análise": id_analise,
                "Etapa": etapa['indice_etapa'] + 1,
                "Equipamento": etapa['nome_equipamento'],
                "Dia": f"{etapa['nome_dia']} (Dia {etapa['indice_dia'] + 1})",
                "Horário": etapa['intervalo_horas']
            })

        if etapas:
            lista_analise.append({
                "Análise": id_analise,
                "Etapa": "Concluído",
                "Equipamento": "-",
                "Dia": f"{nome_dia_conclusao} (Dia {indice_dia_conclusao + 1})",
                "Horário": f"{hora_conclusao:02d}h00"
            })


    df_analise = pd.DataFrame(lista_analise)
    df_analise.set_index("Análise", inplace=True)

    print("\n### Visão por Análise\n")
    display(df_analise)

    lista_equipamento = []

    for indice_dia in range(DIAS):
        nome_dia = nomes_dias.get(indice_dia, f"Dia {indice_dia + 1}")
        if eventos_equipamento_agrupados_diariamente[indice_dia]:
            equipamentos_ordenados_para_dia = sorted(eventos_equipamento_agrupados_diariamente[indice_dia].keys(), key=lambda x: x.value.nome)
            for membro_enum_equipamento in equipamentos_ordenados_para_dia:
                eventos_para_equipamento_no_dia = eventos_equipamento_agrupados_diariamente[indice_dia][membro_enum_equipamento]
                eventos_para_equipamento_no_dia.sort(key=lambda x: x['intervalo'])
                for item in eventos_para_equipamento_no_dia:
                    if item['tipo'] == 'limpeza':
                        lista_equipamento.append({
                            "Dia": f"{nome_dia} (Dia {indice_dia + 1})",
                            "Equipamento": membro_enum_equipamento.value.nome,
                            "Horário": item['intervalo_horas'],
                            "Evento": item['id_analise']
                        })
                    else:
                        lista_equipamento.append({
                            "Dia": f"{nome_dia} (Dia {indice_dia + 1})",
                            "Equipamento": membro_enum_equipamento.value.nome,
                            "Horário": item['intervalo_horas'],
                            "Evento": f"Análise {item['id_analise']}"
                        })

    df_equipamento = pd.DataFrame(lista_equipamento)

    print("\n### Visão por Equipamento\n")
    display(df_equipamento)